### ISSUE TITLE
Filter by date ranges

### ISSUE THREAD

**Issue by fastlanedevel** [creecros/Creecros_Filter_Pack#7]
Hi,
first of all thanks for your effort in kanboard filtering.

I am looking after a way to filter tasks in an interval of dates (attribute could be modified, closed, started, etc) which is not using an absolute date value range but a relative one to today, this week, etc.

Typical usage example: show all the tasks closed between this week and two weeks ago.

It seems that existing filters either cannot realize a date range (boolean operations not working) or the attributes with range cannot take relative dates as arguments.

Many thanks for your help.

**Comment by creecros** [comment]
agree, I believe the issue should be addressed on Kanboard as a bug report. I spent a little bit of time playing with it and reviewing the code, and couldn't even find where it convert strings to time, I could probably find a work around and create a seperate filter, but I feel like it should be fixed in the core.
